#*******************************************************************************
#* makefile.mk
#*------------------------------------------------------------------------------
#* Makefile used to generate the Application binaries (GNU ARM format).
#* This file was automatically generated by IngeDev. Please, do not edit!
#*******************************************************************************

#-------------------------------------------------------------------------------
# General constants
#-------------------------------------------------------------------------------
EMPTY :=
SPACE := $(EMPTY) $(EMPTY)

#-------------------------------------------------------------------------------
# Project and file names
#-------------------------------------------------------------------------------
# Project name
PROJECT_NAME    := SDLC_SAMPLE
# Compiler version
COMPILER_VERSION	:= GNU ARM 3.4.3
# Configuration name
CFG_NAME        := GNU_ARM_DEBUG
# Target file name (without extension)
TRG_FILE_NAME   := SDLC_SAMPLE
# Startup object file name
STARTUP_OBJ_NAME:= cstartup.o
# Mapping file name
MAPPING_DEF_NAME:= mapping.def


#-------------------------------------------------------------------------------
# Directories
#-------------------------------------------------------------------------------
# Binaries directory
BIN_DIR         := Bin
# Object directory
OBJ_DIR         := Obj
# Build files directory
BUILD_FILES_DIR := BuildFiles

#-------------------------------------------------------------------------------
# Input files path for the current configuration
#-------------------------------------------------------------------------------
# Build files path
BUILD_FILES_PATH:= $(BUILD_FILES_DIR)/$(CFG_NAME)

#-------------------------------------------------------------------------------
# Output files path for the current configuration
#-------------------------------------------------------------------------------
# Object files path
OBJ_PATH        := $(OBJ_DIR)/$(CFG_NAME)
# Binary files path
BIN_PATH        := $(BIN_DIR)/$(CFG_NAME)

#-------------------------------------------------------------------------------
# Compiler, linker, assembler, ...
#-------------------------------------------------------------------------------
# Gnu Compiler executable
CC              := arm-elf-gcc.exe
# Gnu Assembler executable
AS              := arm-elf-as.exe
# Gnu Linker executable
LD              := arm-elf-ld.exe
# Gnu binary file transforming executable
OBJ_COPY        := arm-elf-objcopy.exe
# Gnu binary sections size executable
SIZE            := arm-elf-size.exe

#-------------------------------------------------------------------------------
# Gnu Win32 tools
#-------------------------------------------------------------------------------
# Remove tool
RM              := rm.exe -fr
# Make directory tool
MKDIR           := mkdir.exe -p
# Copy tool
CP              := cp.exe
# Printf tool
PRINTF          := printf.exe

#-------------------------------------------------------------------------------
# Includes path used in compilation process
#-------------------------------------------------------------------------------
INCLUDES_PATH   := \
-I"Inc" \
-I"C:/Arquivos de programas/SDK30/SDK 7.5.1/SDK/inc" \

#-------------------------------------------------------------------------------
# Libraries to be included during link operation
#-------------------------------------------------------------------------------
LIBS            := \
C:/Arquivos\ de\ programas/SDK30/SDK\ 7.5.1/SDK/lib_gnu/eft30.lib \
C:/Arquivos\ de\ programas/SDK30/SDK\ 7.5.1/SDK/lib_gnu/trap.lib \
C:/Arquivos\ de\ programas/SDK30/SDK\ 7.5.1/SDK/lib_gnu/PinLib.lib \
C:/Arquivos\ de\ programas/SDK30/SDK\ 7.5.1/SDK/lib_gnu/IAPP.lib \
C:/Arquivos\ de\ programas/SDK30/SDK\ 7.5.1/SDK/lib_gnu/AVL.lib \
C:/Arquivos\ de\ programas/SDK30/SDK\ 7.5.1/SDK/lib_gnu/LinkLayerExeInterface.lib \
C:/Arquivos\ de\ programas/SDK30/SDK\ 7.5.1/SDK/lib_gnu/SEC.lib \
C:/Arquivos\ de\ programas/SDK30/SDK\ 7.5.1/SDK/lib_gnu/dll_wifi.lib \
C:/Arquivos\ de\ programas/SDK30/SDK\ 7.5.1/SDK/lib_gnu/FTP_.lib \
C:/Arquivos\ de\ programas/SDK30/SDK\ 7.5.1/SDK/lib_gnu/SSL_.lib \
C:/Arquivos\ de\ programas/SDK30/SDK\ 7.5.1/SDK/lib_gnu/IP_.lib \
C:/Arquivos\ de\ programas/SDK30/SDK\ 7.5.1/SDK/lib_gnu/SNMP_.lib \
C:/Arquivos\ de\ programas/SDK30/SDK\ 7.5.1/SDK/lib_gnu/IMG_.lib \

#-------------------------------------------------------------------------------
# System libraries to be included during link operation
#-------------------------------------------------------------------------------
SYSTEM_LIBS     := \
-L C:/Arquivos\ de\ programas/Ingenico/IngeDev_7/plugins/com.ingenico.ingedev.telium.bin.win32.gnuarm.v343_7.5.0.0/os/win32/GNUARM/3.4.3/arm-elf/lib/thumb/soft/interwork -lsupc++ \
-L C:/Arquivos\ de\ programas/Ingenico/IngeDev_7/plugins/com.ingenico.ingedev.telium.bin.win32.gnuarm.v343_7.5.0.0/os/win32/GNUARM/3.4.3/arm-elf/lib/thumb/soft/interwork -lc \
-L C:/Arquivos\ de\ programas/Ingenico/IngeDev_7/plugins/com.ingenico.ingedev.telium.bin.win32.gnuarm.v343_7.5.0.0/os/win32/GNUARM/3.4.3/lib/gcc/arm-elf/3.4.3/thumb/soft/interwork -lgcc 

#-------------------------------------------------------------------------------
# Compilation and link input files
#-------------------------------------------------------------------------------
# Mapping file location (used during link process)
MAP_DEF_LOCATION:= $(BUILD_FILES_PATH)/$(MAPPING_DEF_NAME)

#-------------------------------------------------------------------------------
# Result output files
#-------------------------------------------------------------------------------
# Binary file
BINARY_FILE     := $(BIN_PATH)/$(TRG_FILE_NAME).BIN

#-------------------------------------------------------------------------------
# Intermediate files
#-------------------------------------------------------------------------------
# Result map file location
INTER_MAP_FILE  := $(OBJ_PATH)/$(TRG_FILE_NAME).map
# AXF file location
INTER_AXF_FILE  := $(OBJ_PATH)/$(TRG_FILE_NAME).axf
# ELF file location
INTER_ELF_FILE  := $(OBJ_PATH)/$(TRG_FILE_NAME).elf

#-------------------------------------------------------------------------------
# Default compiler, linker, assembler options
#-------------------------------------------------------------------------------
# Default compiler options
CC_DEF_OPTS     := -g -c -Wall -Wcast-align -mthumb-interwork -mlittle-endian -msoft-float -pipe -mcpu=arm920t -fomit-frame-pointer -fshort-enums -mstructure-size-boundary=8
# Default assembler options
AS_DEF_OPTS     := -mthumb-interwork -EL -mno-fpu
# Default linker options
LD_DEF_OPTS     :=  -Map $(INTER_MAP_FILE)

#-------------------------------------------------------------------------------
# Specific compiler, linker, assembler options
#-------------------------------------------------------------------------------
# Specific compiler options
CC_SPEC_OPTS    := -DING_TELIUM -mthumb -fno-exceptions  -D_ING_GNU_ARM_DEBUG
CC_SPEC_OPTS    +=  -D_EXPORT_ -D_EFT30_
CC_SPEC_OPTS    +=  -D_ING_APPLI_BINARY_NAME='"SDLC_SAMPLE"' -D_ING_APPLI_FAMILY='"SDLC_SAMPLE"' -D_ING_APPLI_TYPE=0x6e -D_ING_APPLI_CURRENT_CONFIG_NAME='"GNU_ARM_DEBUG"' -D_ING_APPLI_FULL_BINARY_NAME='"SDLC_SAMPLE.AGN"' -D_ING_APPLI_TELIUM1_FULL_BINARY_NAME='"SDLC_SAMPLE.SGN"' -D_ING_APPLI_TELIUM2_FULL_BINARY_NAME='"SDLC_SAMPLE.AGN"' -D_ING_APPLI_TELIUM_COMPATIBILITY='"Telium_2"' -D_ING_APPLI_SIGN_MODE='"Unsigned"' -D_ING_APPLI_CATALOG_FILE_EXTENSION='"M4X"' -D_ING_APPLI_CURRENT_CONFIG_TOOLCHAIN_ROOT_LOCATION='"C:/Arquivos\ de\ programas/Ingenico/IngeDev_7/plugins/com.ingenico.ingedev.telium.bin.win32.gnuarm.v343_7.5.0.0/os/win32/GNUARM/3.4.3"' $(INCLUDES_PATH)
# Specific assembler options
AS_SPEC_OPTS    := -mthumb  --defsym _ING_GNU_ARM_DEBUG=1
AS_SPEC_OPTS    +=  --defsym _EXPORT_=1 --defsym _EFT30_=1
AS_SPEC_OPTS    +=  --defsym _ING_APPLI_BINARY_NAME='"SDLC_SAMPLE"' --defsym _ING_APPLI_FAMILY='"SDLC_SAMPLE"' --defsym _ING_APPLI_TYPE=0x6e --defsym _ING_APPLI_CURRENT_CONFIG_NAME='"GNU_ARM_DEBUG"' --defsym _ING_APPLI_FULL_BINARY_NAME='"SDLC_SAMPLE.AGN"' --defsym _ING_APPLI_TELIUM1_FULL_BINARY_NAME='"SDLC_SAMPLE.SGN"' --defsym _ING_APPLI_TELIUM2_FULL_BINARY_NAME='"SDLC_SAMPLE.AGN"' --defsym _ING_APPLI_TELIUM_COMPATIBILITY='"Telium_2"' --defsym _ING_APPLI_SIGN_MODE='"Unsigned"' --defsym _ING_APPLI_CATALOG_FILE_EXTENSION='"M4X"' --defsym _ING_APPLI_CURRENT_CONFIG_TOOLCHAIN_ROOT_LOCATION='"C:/Arquivos\ de\ programas/Ingenico/IngeDev_7/plugins/com.ingenico.ingedev.telium.bin.win32.gnuarm.v343_7.5.0.0/os/win32/GNUARM/3.4.3"' $(INCLUDES_PATH)
# Specific linker options
LD_SPEC_OPTS    := 

#-------------------------------------------------------------------------------
# Compiler, linker, assembler options
# default + specific options
#-------------------------------------------------------------------------------
# Compiler options
CC_OPTS         := $(CC_DEF_OPTS) $(CC_SPEC_OPTS)
# Assembler options
AS_OPTS         := $(AS_DEF_OPTS) $(AS_SPEC_OPTS)
# Linker options
LD_OPTS         := $(LD_DEF_OPTS) $(LD_SPEC_OPTS)

#-------------------------------------------------------------------------------
# SRC_OBJS is the list of the project object files
#-------------------------------------------------------------------------------
SRC_OBJS        := \
$(OBJ_PATH)/Main.o \
$(OBJ_PATH)/Entry.o \

#-------------------------------------------------------------------------------
# Dependencies
#-------------------------------------------------------------------------------
DEPENDENCIES    := \
$(BUILD_FILES_PATH)/makefile.mk

#===============================================================================
# Rule to make the project
#===============================================================================
#-------------------------------------------------------------------------------
# Rule for the binary files generation
#-------------------------------------------------------------------------------
$(BINARY_FILE): $(INTER_ELF_FILE) 
	$(OBJ_COPY) -O binary $(INTER_AXF_FILE) $@
	@$(PRINTF) "'$@' binary file generated.\n"

#===============================================================================
# Rule for the link process
#===============================================================================
#-------------------------------------------------------------------------------
# Rule for the axf file generation
#-------------------------------------------------------------------------------
$(INTER_AXF_FILE): $(MAP_DEF_LOCATION) $(SRC_OBJS) $(LIBS)
	@$(PRINTF) "'$@' link in progress...\n"
	@$(CP) "C:\Arquivos de programas\Ingenico\IngeDev_7\plugins\com.ingenico.ingedev.telium.core_7.5.1.0\defaultSystemFiles\Obj\gnu_arm\$(STARTUP_OBJ_NAME)" "$(OBJ_PATH)"
	$(LD) $(LD_OPTS) -T $< -o $@ $(SRC_OBJS) $(OBJ_PATH)/$(STARTUP_OBJ_NAME) -\( $(LIBS) -\) $(SYSTEM_LIBS)

#-------------------------------------------------------------------------------
# Rule for the elf file generation
#-------------------------------------------------------------------------------
$(INTER_ELF_FILE): $(INTER_AXF_FILE)
	$(SIZE) -A $< > $@

#===============================================================================
# Rule for the compilation process
#===============================================================================
ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Main.d
endif
$(OBJ_PATH)/Main.o: Src/Main.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'Src/Main.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Main.o)
	@$(PRINTF) "done!\n"
endif

ifneq ($(MAKECMDGOALS), clean)
-include $(OBJ_PATH)/Entry.d
endif
$(OBJ_PATH)/Entry.o: Src/Entry.c $(DEPENDENCIES) $(EXTRA_DEPENDENCIES)
	@$(PRINTF) "'Src/Entry.c' compilation in progress...\n"
	$(CC) $(CC_OPTS) -MMD -MP -o "$@" "$<"
ifeq ($(MAKECMDGOALS), $(OBJ_PATH)/Entry.o)
	@$(PRINTF) "done!\n"
endif

#===============================================================================
# Rule for project name and configuration name display
#===============================================================================
.PHONY: displayInfo
displayInfo:
	@$(PRINTF) "                                     *-*-*\n"
	@$(PRINTF) "--- Project '$(PROJECT_NAME)', Configuration '$(CFG_NAME)', Compiler '$(COMPILER_VERSION)' ---\n"

#===============================================================================
# Rule for output directories creation
#===============================================================================
.PHONY: createOutputDirs
createOutputDirs:
	@$(MKDIR) "$(OBJ_PATH)"
	@$(MKDIR) "$(BIN_PATH)"

#===============================================================================
# Make build rule
#===============================================================================
.PHONY: build
build: displayInfo createOutputDirs $(BINARY_FILE)
	@$(PRINTF) "done!\n"

#===============================================================================
# Make clean rule
#===============================================================================
.PHONY: clean
clean: displayInfo
	@$(PRINTF) "deleting intermediate files...\n"
	@$(RM) "$(BINARY_FILE)"
ifneq "$(wildcard $(OBJ_PATH)/*.*)" ""
	@$(RM) "$(OBJ_PATH)/*.*"
endif
	@$(PRINTF) "done!\n"
